# Generated by Django 2.2.7 on 2019-11-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0002_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='postal_code',
            field=models.TextField(null=True),
        ),
    ]
