# Generated by Django 2.2.7 on 2019-11-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0005_auto_20191105_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='color',
            field=models.TextField(),
        ),
    ]
